### ISSUE TITLE
340 display support

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#644]
Notes for helping @philbudne adding 340 display support to the KA10 simulator, for use with ITS.

ITS applications that are checked and working:

- [x] Exec DDT (older NTSDDT N77h works, see #794 and #1460)
- [x] Spacewar!, standalone
- [x] Spacewar!, timesharing (hangs ITS, see #782)
- [x] PEEK
- [ ] TECO
- [ ] MACDMP #449 
- [ ] MAGDMP (just hangs)
- [x] FED (font editor) #289 (displays font then crashes, see https://github.com/rcornwell/sims/issues/60)
- [ ] DECUUO (problem running SUDS #792)
- [x] 11SIM #197 (run PDP-11 Dazzle Dart? #899; or 11LOGO #889)
- [x] LD10 #651
- [x] PDSET
- [x] MLIFE #692 
- [ ] Dazzle Dart #868 
- [ ] SHRDLU #147 
- [x] LLOGO #884 
- [ ] Patterson's Worm #929 
- [ ] GAS simulation #931
- [ ] GALAXY #932
- [x] MacHack VI #933
- [ ] PORNIS #935
- [ ] FLIGHT #893 
- [x] 340D #778

**Comment by larsbrinkhoff** [comment]
Get @rcornwell's KA10 simulator: http://github.com/rornwell/sims.  The tape support is in flux.  At this moment the best bet is to edit the next last line in `mt_srv` to `sim_activate(uptr, 800);`.  Then `make ka10`.

**Comment by larsbrinkhoff** [comment]
Get the ka10 branch from http://github.com/PDP-10/its.  For now, the its repository and the sims repository need to sit side by side.

Also get the subrepositories.  Either `git clone --recursive`, or `git submodule update --init`.

To build ITS from scratch, type `make all`.  This may not work yet.

I will put disk images online.

**Comment by larsbrinkhoff** [comment]
To assemble ITS with 340 support, edit SYSTEM; CONFIG >.  Go to the section for ML and add `DEFOPT 340P==1`.  Assemble ITS for ML.

**Comment by larsbrinkhoff** [comment]
At this point TECO, and by extension EMACS, doesn't work which makes it hard to do work inside ITS.

**Comment by larsbrinkhoff** [comment]
Dumping ITS in DSKDMP:

```
L$ddt
T$its bin
$U
M$salv bin
D$nits
```

Dumping ITS in timesharing DDT:

```
its$J
$1L .; @ ddt
$$1L .; salv bin
$$L .; its bin
$Y .; @ nits
:kill
```

File file names may differ.

**Comment by larsbrinkhoff** [comment]
To boot ITS, start sims/BIN/ka10 and pass it a suitable configuration file such as its/build/ka/boot.

The simulator will boot into DSKDMP.  Type `its` and Enter.  (Or `nits` if you dumped to that file name.)  Then $G to start.

**Comment by rmaldersoniii** [comment]
Lars wrote :
 _At this point TECO, and by extension EMACS, doesn't work which makes it hard to do work inside ITS._

I don't understand the context for this remark. I have been using EMACS on the kn10-ks-its variant of ITS for several weeks (although currently I'm not working on ITS at all). What seems to be the issue, Lars?

**Comment by larsbrinkhoff** [comment]
Yes @rmaldersoniii, there's a lot of context missing.

I wrote these comments to help Phil get started adding 340 display support for use with ITS.  But it's not the stock SIMH, but @rcornwell's KA10 version which is in development.

We have tried to build TECO on this KA10 simulator, but TECO craches when started.

**Comment by larsbrinkhoff** [comment]
Here are prebuilt KA ITS image files:  
http://lars.nocrew.org/its/budd/

**Comment by larsbrinkhoff** [comment]
There is some problem when purifying jobs, and/or purified PDUMP files.  So stay away from that.

I build TECO without purification, and it seems to work.

**Comment by larsbrinkhoff** [comment]
Sorry, I was wrong about EMACS.  Jumped to conclusions.

EMACS does work in the KA ITS image.

**Comment by larsbrinkhoff** [comment]
I made some mistakes building the KA ITS disk images.  Some files were for KS ITS.

I have now updated the images.  I tested building ITS with 340P enabled, and at least it boots.

**Comment by larsbrinkhoff** [comment]
By the way, it might be more convenient to put the binaries on an ITS disk image, rather than paper tape.  At least if there's a need to edit and build programs.  Anything that does into the . directory and has @ as first file name is easy to start from DSKDMP which can be booted off paper tape.

**Comment by larsbrinkhoff** [comment]
@philbudne I can't hold off my questions anymore...

I'm so curious to test this!  Is there anything available?

Did you get NTS DDT to do anything useful with the display?  Have you tested anything other than Spacewar?

**Comment by philbudne** [comment]
I didn't get anywhere with exec DDT built for display (kept outputting
spaces and/or newlines on the TTY console), and I switched to
stand-alone spcwar.rim when you built it for me, and haven't gone back
to ITS yet.

I've just forked the sims repo and pushed the cleaned up to branch
mit340 of https://github.com/philbudne/sims

Hopefully I've gotten the spacewar switches sorted out.  I finally
gave in and straightened it out doing using an idiom common in PDP-10
programming, translated to C.  See spacewar_switches in
display/display.h

**Comment by rcornwell** [comment]
Code looks pretty good. I can copy the display directory and update the SCP tree if you want.

**Comment by larsbrinkhoff** [comment]
Cool, thanks!  To build it, I added `TYPE340=y` to the make command line.

**Comment by philbudne** [comment]
I can submit a PR if that makes it easier...

phil

**Comment by rcornwell** [comment]
I am trying to keep changes to SCP and my sim separate. When the simulator is ready to move to the main simH tree, I will run a git command to extract all the changes for the KA10 tree and apply them to a branch on SimH, then Mark will merge it up. Remember no tabs and dos format files.

When you are happy with the changes, you can move them to the master branch and submit a pull request.

**Comment by rcornwell** [comment]
I pushed out a new version of my sims tree with display added. Please redo your pull request with latest version. Also all commit messages MUST start with KA10:!

**Comment by larsbrinkhoff** [comment]
@philbudne Are you doning anything more with the 340?  Or do you consider this done?

I will test some more applications, both standalone and timesharing.

**Comment by philbudne** [comment]
> Are you doning anything more with the 340?  Or do you consider this done?
> I will test some more applications, both standalone and timesharing.

I'm not actively working on the display code proper (but am plotting a
way to do spacewar consoles in software).

Have you gotten any T/S program working with the display?
If you have, then I think it's fair to close the ticket.

I don't remember seeing any code that depended on the DSDEV[N] devices
returning any status or data.  But I still wouldn't be surprised if
ITS turns up some issue in my ka10_dpy.c interface code that non-T/S
SPCWAR didn't uncover....

p

**Comment by larsbrinkhoff** [comment]
I have just now build ITS with 340P=1.

Spacewar doesn't work, but it's probably due to using some kind of real-time feature.  It gets to here:

            .SUSET [.SMASK,,[%PIRLT]]       ;ENABLE RLT

And promptly hangs the system.

I'll try something else.

**Comment by larsbrinkhoff** [comment]
Built a new PEEK with 340P==1.  Typed ^Y hoping to see some 340 graphics.  Hung system.

**Comment by larsbrinkhoff** [comment]
Started PDSET.  Typed S.  Hung system.

**Comment by larsbrinkhoff** [comment]
@philbudne PDSET seems like a nice test case for this.

Start PDSET and type S.  It will execute .DSTART.  It seems to do its thing, and come back to URETJ1 to do a skip return to user space.  But it doesn't get there.  I interrupted the simulator, and PC was at LPTBR2-1, in the IFN 340P block.  So it seems there are interrupts happening.  Restarting and stopping randomly, the PC seems to hang out there a lot.

Can you check if the interrupt handling seems ok for this case?

**Comment by philbudne** [comment]
> Can you check if the interrupt handling seems ok for this case?

OK, will check it out.  Maybe tonight, maybe later.

Is there a way to break into Exec DDT from T/S?

**Comment by larsbrinkhoff** [comment]
It would be nice to get to EDDT from timesharing, but I haven't found a way.  Except maybe doing :LOCK to go through a full shutdown sequence, but I tried that yesterday and it didn't work.

What I do is to try to set breakpoints before starting ITS.  Sometimes I forget and have to start over.  ITS is quite good about uncontrolled shutdowns, so I'll just exit from the emulator.

And before you ask, no, ^N or $^N doesn't work.

**Comment by larsbrinkhoff** [comment]
Built SYSTEM; DDT with 340 support.  Had to comment out `dpysw==:0` first.

Once started from DSKDMP, it prints `100/` and an endless number of space characters.

**Comment by philbudne** [comment]
> and an endless number of space characters.

I saw the same thing, and it's why I switched to stand-alone SPCWAR.

It doesn't seem to be related to the T/S issue
(expecting sign bit set in CONI DIS, results)

**Comment by larsbrinkhoff** [comment]
New app: Bill Gosper's MLIFE.

When I start it I get a Type 30 display, according to the window title.  @philbudne, I though there was only 340 emulation for the KA10?

**Comment by larsbrinkhoff** [comment]
Here's MLIFE; standalone and source.    
http://lars.nocrew.org/its/mlife.tape

**Comment by philbudne** [comment]
> New app: Bill Gosper's MLIFE.

Neat!  I haven't looked: does it use the light pen?
Does it work???

Are magtapes working now?
How do I attach and extract a .tape file?

> When I start it I get a Type 30 display, according to the window title.  @philbudne, I though there was only 340 emulation for the KA10?

That's VERY odd, the only display_init call in type340.c is
        display_init(DIS_TYPE340, 1, u); /* XXX check return? */

And the params for DIS_TYPE340 are:
display.c:    { DIS_TYPE340, "Type 340", &color_p17, NULL, 1024, 1024 }

**Comment by larsbrinkhoff** [comment]
> Neat!  I haven't looked: does it use the light pen?

Not as far as I can see.

> Does it work???

I don't see anything in the window.  I didn't try typing at the console.

> Are magtapes working now?
> How do I attach and extract a .tape file?

Yes, they do.  In the console, type ^E and then `at mta0 mlife.tape`.  Then `c` to continue.  In ITS, `:dump`, `load`.  FILE= `*; * *`.

**Comment by larsbrinkhoff** [comment]
Apparently, the MIT-AI 340 display does something undocumented with CONI bit 0.  The manual only documents CONI bits 18-35, which is also the usual range for devices to provide.  Phil has confirmed that CONI is capable of getting a full 36-bit word from the bus, so possibly this was an MIT hardware modification.

The lack of bit 0 in  the CONI status word causes the code below to fail.

```
        CONI DIS,A      ;Get display status
        TRNN A,77       ;Any PI channels?
        JRST LPTBR2     ;No, check other device interrupts.
        CONSZ DIS,7400  ;Edge, light pen, or stop condition?
        JUMPL A,SRECYC  ;Bit 0 set, handle special display interrupt channel

**Comment by larsbrinkhoff** [comment]
ITS 785 from 1973 also makes use of CONI bit 0, so this goes back to ITS prehistory.

**Comment by larsbrinkhoff** [comment]
@philbudne, check this other snippet from ITSDEV:

```
SRCYRB: CONI DIS,A      ;Get display status
        SKIPGE A        ;Skip if bit 0 is zero.
        CONO DIS,100    ;WOULD ASSIGN IF IDLE
        MOVE A,[JSR DIGNOR]
        JRST SRCYB1
```

I haven't read all the 340 code so I'm not sure when this is called.  But remember that the MIT-AI 340 was attached to both the PDP-6 and the PDP-10.  There is a special device for assigning peripherals to the 6 or the 10.  Assignment is done automatically when a processor issues a CONO, and then you have to explicitly deassign a device when it's not in use any more.

Now see what this bit 0 does.  If it's zero, SRECY will not be called.  And SRCYRB will not do a CONO.

Maybe bit 0 indicates that the display is assigned to some processor, or that it's assigned to the PDP-10?

**Comment by larsbrinkhoff** [comment]
Got it.  It's explained in [HW memo 1](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/ITS_Hardware_Memo_1.pdf).

Every peripheral on the shared I/O bus has a card called X100 which remembers if the peripheral is unassigned, assigned to the PDP-6, or assigned to the PDP-10.

> There is also another feature built into the X100 card, which is a gate that is normally driven by the device CONI level and will read in a 1 or 0 on bit 0.  This allows the processor to check for a successful assignment, because if the device is assigned to the other processor then the device CONI level will not be developed and a 1 will not be read in on bit 0.

**Comment by larsbrinkhoff** [comment]
I had to supress a scream of joy waking up my kid when I saw PEEK displaying on the 340!

**Comment by larsbrinkhoff** [comment]
MLIFE does... something.  I got it to display "6214" to the upper right.  But I don't know how to operate it.

**Comment by larsbrinkhoff** [comment]
PDSET works.  "-1S" to activate.  Maybe this will be my new wall clock.

**Comment by larsbrinkhoff** [comment]
Exec DDT still prints lots of spaces.

**Comment by philbudne** [comment]
> PDSET works.  "-1S" to activate.  Maybe this will be my new wall clock.

Hasn't worked for me :-(

**Comment by larsbrinkhoff** [comment]
Strange.  I didn't do anything to make it work.  Or, not anything I'm aware of. 

This is what I remember doing:

- Made a new ITS with 340P==1.  Assemble, then dump in DSKDMP.
- Assembled a new PEEK.  I said /T to MIDAS and then 340P==1.  (By the way, please use IFNDEF for switches in programs.)
- Edited exec DDT to say `dpysw==:1`.
- Did nothing to PDSET or MLIFE, because the 340 code is unconditional.

**Comment by larsbrinkhoff** [comment]
Probably have to set the ttytyp %TT340 bit on the ITS console to make DECUUO (and SUDS) use the 340.

**Comment by larsbrinkhoff** [comment]
Timesharing SPCWAR doesn't seem to work.  Hangs ITS completely.

**Comment by philbudne** [comment]
Ah... Helps if I set the system time first!

Pleasant surprise that one simulated bit was all that was needed!

p

**Comment by philbudne** [comment]
> Timesharing SPCWAR doesn't seem to work.  Hangs ITS completely.

Was just about to ask that question, but figured you'd tell me
if there was a problem!  So much for "just one bit"!

**Comment by larsbrinkhoff** [comment]
I patched FED to make it use the 340.  This patching will not be necessary once ITS knows the console TTY is "near" the 340 display.

I read in a font file, and FED displayed it.  Then ITS crashed.

```
READING:  DSK:FONTS;20FG KST
UUO WITH PI IN PROGRESS  10/7/1975 11:33:23
PI LEVEL 6 BUGHALT.  FIND A WIZARD OR CONSIDER TAKING A CRASH DUMP.
THE SYSTEM HAS CRASHED AND CANNOT BE REVIVED WITHOUT EXPERT ATTENTION.
IF YOU CAN'T FIND HELP, RELOAD THE SYSTEM.6
YOU ARE NOW IN DDT. 1 ! 6/5/1975 21:32:05
BUGPC/   CAI UUOH0+2   $Q-2/   CONSZ PI,TTYST2+4

**Comment by larsbrinkhoff** [comment]
> Was just about to ask that question, but figured you'd tell me if there was a problem!

I'll report here and check off boxes in the top comment.

**Comment by larsbrinkhoff** [comment]
I'm kind of giving up on SUDS, at least for now.  Maybe @ams will take it from here.

**Comment by larsbrinkhoff** [comment]
Checking what FED does.  It reads a font file, does some processing, and calls .DSTART.  Then ITS promply crashes.  It reliably ends up in TTYST2+4 which is 0, hence the BUGHALT.  TTYST2 is a table with data, so ITS has no business jumping there.

Before the crash the font briefly flashes by on the display, so it seems like the display list should be ok.  At least most of it.

**Comment by larsbrinkhoff** [comment]
FED:  
ITS handles a 340 interupt and jumps to SRECYC.  It goes through everything in the handler and returns through LPTBRK.  Eventually we find ourselves at UEXIT, whish is trying to restore the PC to 310000,,CFHAH2+12.  Proceeding from there, we get a crash.

**Comment by larsbrinkhoff** [comment]
Here's the latest info on FED:  
https://github.com/rcornwell/sims/issues/60

**Comment by larsbrinkhoff** [comment]
I assembled MAGDMP with support for 340, but when I tried to run it, it just hung.  It didn't even print "MAGDMP".

**Comment by larsbrinkhoff** [comment]
Rich has merged the 340 CONI fix, so I'm preparing a pull request to update the KA10 simulator and ITS for using the display.

**Comment by larsbrinkhoff** [comment]
PEEK makes use of the light pen.

**Comment by larsbrinkhoff** [comment]
Loading a drawing in SUDS:

    *:dec draw;d /meta
    *^C I

I'll check how to have it displayed later.

**Comment by larsbrinkhoff** [comment]
AIM-240A says 11SIM can display three PDP-11 consoles and one simulator information view simultaneously on the 340.

**Comment by TheFausap** [comment]
Is it possible to use Emacs with 340 display ?

**Comment by larsbrinkhoff** [comment]
At this point, no.  The 340 can display text, but it's not a text terminal and it doesn't have a keyboard.  There could be a terminal emulator which displayed on the 340.  And there was; one that emulated a Datapoint.  But we don't have any such program today.  It probably wouldn't be too hard to make one though.  Maybe a suitable project for a beginner MIDAS programmer?

**Comment by TheFausap** [comment]
Oh, I'd like to write some MIDAS code, but I don't know how to find the proper documentation about 340 and some introductory text about MIDAS (I tried to find something on bitsavers with no luck). :-)

**Comment by larsbrinkhoff** [comment]
If you really like to give it a try, we can provide you with all necessary documentation.  ITS already comes with almost everything.  Except for 340 programming, you won't need to go to Bitsavers.  For starters, read these:

- HACTRN: https://github.com/PDP-10/its/blob/master/doc/DDT.md
- EMACS: https://github.com/PDP-10/its/blob/master/doc/EMACS.md
- MIDAS hello world: https://github.com/PDP-10/its/blob/master/doc/hello-midas.md
- PDP-10 instruction set: https://github.com/PDP-10/its/blob/master/doc/info/pdp-10.15

There are some more links to ITS documentation here: https://github.com/PDP-10/its/tree/master/doc

**Comment by larsbrinkhoff** [comment]
I'd like there to be a complete set of introductory .md files in the doc directory.  If there's some basic operation you want to do and it's not covered there, let me know and I'll try to add it.  Or point to the full documentation.

**Comment by larsbrinkhoff** [comment]
Tested 11SIM with 340 display.  It works.  Run `:pdp45` and then at the ! prompt, type `;a ngdis`.

Maybe Dazzle Dart will run in 11SIM.

**Comment by larsbrinkhoff** [comment]
Checked new programs:

- Flight simulator: displays gagues!  Shortly after, veers of into weirdness.
- Dazzle Dart: doesn't work
- Patterson's Worm: interacts on console, but no graphics
- Gas simulation: prints text to console, then hangs.
- GALAXY: displays points for fraction of a second, then blanks.  It's not hung though.

**Comment by larsbrinkhoff** [comment]
Also tried to assemble 11LOGO to run in 11SIM with 340 display, but without success.

**Comment by atsampson** [comment]
A couple of mentions of early TECO on the 340.

Mark Crispin in news:Pine.OSX.4.64.0512181715300.9510@pangtzu.panda.com wrote:

> The ultimate source of TOPS-10 TECO was the reimplementation of Dan Murphy's PDP-1 TECO on the PDP-6 at the MIT AI Lab; that is, a very early version of ITS TECO.  That program most definitely had display support, and was always used on the 340(?) display. [...] It was a mystery to the original authors of TECO that anyone would ever consider TECO usable without a display.

**Comment by larsbrinkhoff** [comment]
As per #655, we should have a TECO with 340 support.  I have examined it, but not done any tests.

**Comment by larsbrinkhoff** [comment]
Some progress towards timesharing 340 use.  It turns out ITS is doing some clever tricks when it comes to handling the interrupts.

First, there's this interesting code to handle 340 data interrupts.

```
LOC PI0LOC+2*DISCHN                                                             
        JSR DIGNOR      ;340 DISPLAY BLKO GETS PATCHED IN HERE                  
        CONO PI,4000+200_<-SDCHN>       ;HACK HACK
```

As the comment says, the `JSR DIGNOR` will be replaced with a BLKO.  The trick here is when the BLKO pointer runs out.  In this case, the processor will execute the `CONO` instruction, which is a request for an interrupt on the special display interrupt channel SDCHN.  Now, according to DEC manuals, an IO instruction here is disallowed.

Second, here's the code to handle the SDCHN interrupt.  It's shared with the LPT device and some others.

```
LOC PI0LOC+2*LPTCHN
        JSR LPTBRK      ;LPT,DISPLAY,PTP,PTR,OTHER PROCESSOR
IFN 340P,       JSR DRECYC      ;HACK HACK
```

Note in particular the second instruction, `JSR DRECYC`.  Normally, an interrupt on this channel would execute `JSR LPTBRK` and never return back to the seond instruction.

It appears that a programmed interrupt request *during a PI cycle* is special.  This isn't documented by DEC, and was most likely not intended to be used like this.  What happens is that the `CONO PI` instruction is executed during a PI cycle, and PI OV remains active so `JSR DRECYC` is executed.

See how the comment `;HACK HACK` marks both the start and the destination of this trick.

**Comment by philbudne** [comment]
Thanks!

I wonder if there was a way on MC (or did the KL-UDGE include switches
as well as lights?)

**Comment by larsbrinkhoff** [comment]
The code for this is shortly below CKLTIC in ITS.  The console switches are only checked on a KA10.  For KL10, it does something with DTE20 so I guess that's on the 11/40 front end.  For KS10, something is done with the front end SH command.

**Comment by larsbrinkhoff** [comment]
@TheFausap wrote:
> Is it possible to use Emacs with 340 display ?

Now it is, by using the program 340D.  See #778.  There is no keyboard input from the 340 window yet.

**Comment by larsbrinkhoff** [comment]
The older NTSDDT N77H works with the 340, see #794.

**Comment by philbudne** [comment]
neat!

**Comment by larsbrinkhoff** [comment]
The 340 works quite well now, so I think we can close this.

**Comment by larsbrinkhoff** [comment]
A 340 slave display, according to Greenblatt.
![340slave](https://user-images.githubusercontent.com/775050/52856635-3e487e00-3125-11e9-8296-96f9ca447c39.png)
Source: https://archive.org/details/AIfilms/80-cube.mp4

**Comment by larsbrinkhoff** [comment]
TECO 335 displays on the 340.

**Comment by larsbrinkhoff** [comment]
The binary file .; @ TECO also works on the 340.  I learned you have to type ^D to enable the display.

It doesn't like lowercase characters.

**Comment by larsbrinkhoff** [comment]
From [AI memo 238, "ITS Status Report"](https://dspace.mit.edu/bitstream/handle/1721.1/6194/AIM-238.pdf), page 34:

> The prime display facility on the ITS system is a DEC 340 display with extended character generator character set.  This display is placed near a hardwired system teletype terminal and also drives two slave monitor displays, a DEC 343 and a Hewlett-Packard 1300A.
